import { ReceiptDocument, AuditRecord } from '../types';

export function exportReceiptAsJSON(receipt: ReceiptDocument, auditRecord?: AuditRecord) {
  const exportData = {
    meta: {
      exportedAt: new Date().toISOString(),
      system: 'DSDNet-Receipt Research Prototype v2.2',
      complianceDisclaimer:
        'This export is generated by an academic research prototype for evidence review. It does not certify tax compliance or official MyInvois acceptance.'
    },
    receipt: {
      id: receipt.id,
      filename: receipt.filename,
      uploadTimestamp: receipt.uploadTimestamp,
      processedTimestamp: receipt.processedTimestamp,
      overallDecision: receipt.overallDecision,
      processingMethod: receipt.processingMethod,
      degradationType: receipt.degradationType,
      degradationSeverity: receipt.degradationSeverity,
      processingTimeMs: receipt.processingTimeMs,
      reviewer: receipt.reviewerName,
      reviewerNotes: receipt.reviewerNotes
    },
    extractedFields: receipt.fields.map((f) => ({
      name: f.name,
      key: f.key,
      value: f.value,
      originalExtractedValue: f.originalExtractedValue,
      ocrConfidence: f.ocrConfidence,
      traceSupportScore: f.traceSupportScore,
      ruleCheckStatus: f.ruleCheckStatus,
      ruleCheckMessage: f.ruleCheckMessage,
      riskCategory: f.riskCategory,
      decisionStatus: f.decisionStatus,
      isAbstained: f.isAbstained,
      abstentionReason: f.abstentionReason,
      reviewerNote: f.reviewerNote,
      boundingBox: f.boundingBox
    })),
    lineItems: receipt.items,
    auditRecord: auditRecord || {
      auditId: receipt.auditRecordId,
      receiptId: receipt.id
    }
  };

  const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${receipt.id}_dsdnet_verification.json`;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportReceiptAsCSV(receipt: ReceiptDocument) {
  const headers = [
    'Field Name',
    'Extracted Value',
    'OCR Confidence',
    'Trace Support Score',
    'Rule Check Status',
    'Risk Category',
    'Decision Status',
    'Is Abstained',
    'Reviewer Note'
  ];

  const rows = receipt.fields.map((f) => [
    `"${f.name}"`,
    `"${f.value.replace(/"/g, '""')}"`,
    f.ocrConfidence.toFixed(2),
    f.traceSupportScore.toFixed(2),
    `"${f.ruleCheckStatus}"`,
    `"${f.riskCategory}"`,
    `"${f.decisionStatus}"`,
    f.isAbstained ? 'YES' : 'NO',
    `"${(f.reviewerNote || '').replace(/"/g, '""')}"`
  ]);

  const csvContent = [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${receipt.id}_fields_audit.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportAuditRecordAsJSON(record: AuditRecord) {
  const blob = new Blob([JSON.stringify(record, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${record.auditId}_immutable_record.json`;
  a.click();
  URL.revokeObjectURL(url);
}
